### ISSUE TITLE
Can't use the environment variable in the workflow

### ISSUE THREAD

**Issue by charlesmorin** [GINCHER/azure-keyvault#1]
Hi,

I tried this GitHub action in order to authenticate and fetch secrets from our private Azure Key Vault. Looking at the logs, I see something that seems wrong to me:

```
Run gincher/azure-keyvault@v1
`SONARCLOUD-TOKEN` was added to the environment variables as `SONARCLOUD_TOKEN`
::set-env name=SONARCLOUD_TOKEN,::***
`GITHUB-SONARCLOUD-TOKEN` was added to the environment variables as `GITHUB_SONARCLOUD_TOKEN`
::set-env name=GITHUB_SONARCLOUD_TOKEN,::***
```
See the comma following the environment variable name in the `set-env` statement? Is it normal?

Thanks

**Comment by gincher** [comment]
The comma caused by a bug in `@actions/core`, but it seems like it works even with the comma. 

You can see if the ENV variables appended correctly by looking at any of the next steps, for example, in my log (lines 7, 8):
![image](https://user-images.githubusercontent.com/9481884/67814260-44606e00-faac-11e9-8658-5953f8d19a18.png)

If in the next step you can see a problem with the variables, please let me know.

**Comment by charlesmorin** [comment]
Is it supposed to persist between jobs within the same workflow file? I was able to output the environment variables within the same job, but when I try reusing it later in another job within the same workflow file, the value is empty, which breaks the pipeline.

Another question: Do you access the imported secrets using `$VARNAME` or `${{ VARNAME }}`?

Do you have a complete example that you could share here or offline?

Thanks for all that work and your quick response.

**Comment by GINCHER** [comment]
No, because all jobs run separately, the ENV values are not accessible outside their jobs. You'll need to use this action in every job, and I think you'll need to re-login to azure as well.

For the second question, I'm not sure if there is a way to do it at all. If you need to use a different ENV VAR name, you can either change the name of the secret, or run the following step (I didn't tried it):

```yaml
- name: Rename ENV variables   shell: bash
  run: |
    echo '::set-env name=ENVNAME::$ENVVAR'
```

Here is a job I use in a private repository of mine:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@gincher"
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: npm install
        run: npm install
      - name: Download secrets
        uses: gincher/azure-keyvault@v1
        with:
          keyVaultName: "spokesperson"
          secretsFilter: "*"
      - name: Run tests
        run: npm test -- --detectOpenHandles
      - name: compile typescript
        run: npm run build
      - name: npm publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by gincher** [comment]
No, because all jobs run separately, the ENV values are not accessible outside their jobs. You'll need to use this action in every job, and I think you'll need to re-login to azure as well.

For the second question, I'm not sure if there is a way to do it at all. If you need to use a different ENV VAR name, you can either change the name of the secret, or run the following step (I didn't tried it):

```yaml
- name: Rename ENV variables   shell: bash
  run: |
    echo '::set-env name=ENVNAME::$ENVVAL'
```

Here is a job I use in a private repository of mine:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@gincher"
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Download secrets
        uses: gincher/azure-keyvault@v1
        with:
          keyVaultName: "secrets"
          secretsFilter: "*"
      - name: npm install
        run: npm install
      - name: Run tests
        run: npm test -- --detectOpenHandles
      - name: compile typescript
        run: npm run build
      - name: npm publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
