### ISSUE TITLE
Deprecated use of set-env in @v1

### ISSUE THREAD

**Issue by kf6kjg** [GINCHER/azure-keyvault#4]
Using
```yaml
            - name: Fetch key vault secrets
              uses: gincher/azure-keyvault@v1
              with:
                  keyVaultName: ${{ env.KEY_VAULT }}
```
as of today results in
```
Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

It looks like a solution for this was already implemented, namely updating `@actions/core` to 1.2.6 via commit a4f76400936232f34c98de153e5979f8cdc012f0, but it seems that the change hasn't propagated to the release.  Maybe the package.json version minor or patch number needs bumping? After all, this package is still a 1.0.0.
